<?php

namespace Plugin\ProductOptions\Repository;

use Doctrine\Persistence\ManagerRegistry as RegistryInterface;
use Eccube\Doctrine\Query\Queries;
use Eccube\Repository\AbstractRepository;
use Plugin\ProductOptions\Entity\CartOptions;

/**
 * CartOptionsRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartOptionsRepository extends AbstractRepository
{
    /**
     * @var Queries
     */
    protected $queries;

    public const COLUMNS = [
        'id'            => 'd.id',
        'cart_id'       => 'd.cart_id',
        'option_id'     => 'd.option_id',
    ];

    /**
     * CartOptionsRepository constructor.
     *
     * @param RegistryInterface $registry
     */
    public function __construct(RegistryInterface $registry, Queries $queries)
    {
        parent::__construct($registry, CartOptions::class);

        $this->queries = $queries;
    }
}
