<?php

namespace Plugin\ProductOptions\Repository;

use Doctrine\Persistence\ManagerRegistry as RegistryInterface;
use Eccube\Doctrine\Query\Queries;
use Eccube\Repository\AbstractRepository;
use Plugin\ProductOptions\Entity\ProductOptions;

/**
 * ProductOptionsRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductOptionsRepository extends AbstractRepository
{
    /**
     * @var Queries
     */
    protected $queries;

    public const COLUMNS = [
        'id'            => 'd.id',
        'product_id'    => 'd.product_id',
        'option_id'     => 'd.option_id',
    ];

    /**
     * ProductOptionsRepository constructor.
     *
     * @param RegistryInterface $registry
     */
    public function __construct(RegistryInterface $registry, Queries $queries)
    {
        parent::__construct($registry, ProductOptions::class);

        $this->queries = $queries;
    }
}
